### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sabbir2609** [learnwithsumit/uptime-monitoring-api-raw-node#3]
![IMG_20210614_143814.jpg](https://user-images.githubusercontent.com/35517413/121863934-2c3f7000-cd1e-11eb-84e2-197dfaac4627.jpg)

```
npm
run `npm fund' for details
found vulnerabilities
PS C:\Users\Sabbir\Desktop\Node\New folder\uptime-monitoring-api-raw-node> npm start
> raw-node-api-project@1.0.0 start C:\Users\Sabbir\Desktop\Node\New folder\uptime-monitoring-api-raw-node
> nodemon index
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs'
[nodemon) watching path(s):
[nodemon) watching extensions: js,mjs,json
[nodemon] starting `node index index.js
listening to port 3000
this is my payload
events.js:353
throw er; // Unhandled 'error' event
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
at writeAfterEnd (_http_outgoing.js: 694:15)
at Server Response.end (http_outgoing.js:815:7)
at IncomingMessage.canonymous> (C:\Users\Sabbir\Desktop\Node\New folder\uptime-monitoring-api-raw-node\helper
s\handleReqRes.js:62:13)
at IncomingMessage.emit (events.js:388:22)
at endReadableNT (internal/streams/readable.js:1336:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on Server Response instance at:
at writeAfterEndNT (_http_outgoing.js:753:7)
at processTicksAndRejections (internal/process/task_queues.js:83:21) {
code: 'ERR_STREAM_WRITE_AFTER_END'
}
[nodemon] app crashed waiting for file changes before starting...
```

**Comment by sabbir2609** [comment]
> ![IMG_20210614_143814.jpg](https://user-images.githubusercontent.com/35517413/121863934-2c3f7000-cd1e-11eb-84e2-197dfaac4627.jpg)
> 
> 
> ```
> npm
> run `npm fund' for details
> found vulnerabilities
> PS C:\Users\Sabbir\Desktop\Node\New folder\uptime-monitoring-api-raw-node> npm start
> > raw-node-api-project@1.0.0 start C:\Users\Sabbir\Desktop\Node\New folder\uptime-monitoring-api-raw-node
> > nodemon index
> [nodemon] 2.0.7
> [nodemon] to restart at any time, enter `rs'
> [nodemon) watching path(s):
> [nodemon) watching extensions: js,mjs,json
> [nodemon] starting `node index index.js
> listening to port 3000
> this is my payload
> events.js:353
> throw er; // Unhandled 'error' event
> Error [ERR_STREAM_WRITE_AFTER_END]: write after end
> at writeAfterEnd (_http_outgoing.js: 694:15)
> at Server Response.end (http_outgoing.js:815:7)
> at IncomingMessage.canonymous> (C:\Users\Sabbir\Desktop\Node\New folder\uptime-monitoring-api-raw-node\helper
> s\handleReqRes.js:62:13)
> at IncomingMessage.emit (events.js:388:22)
> at endReadableNT (internal/streams/readable.js:1336:12)
> at processTicksAndRejections (internal/process/task_queues.js:82:21)
> Emitted 'error' event on Server Response instance at:
> at writeAfterEndNT (_http_outgoing.js:753:7)
> at processTicksAndRejections (internal/process/task_queues.js:83:21) {
> code: 'ERR_STREAM_WRITE_AFTER_END'
> }
> [nodemon] app crashed waiting for file changes before starting...
> ```

![Screenshot_20210614-185916.png](https://user-images.githubusercontent.com/35517413/121896155-cdd8b880-cd42-11eb-87bd-302f9a475d3b.png) 
> **I think line 62 causing the problem**
